#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# Sovereign Swarm — Interactive Configuration Script
# Run after install to set up API keys, personalization, and preferences.
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()  { echo -e "${CYAN}[INFO]${NC}  $1"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $1"; }

HERMES_HOME="${HOME}/.hermes"
CONFIG_FILE="${HERMES_HOME}/config.yaml"
SOUL_FILE="${HERMES_HOME}/SOUL.md"
AGENTS_FILE="${HERMES_HOME}/AGENTS.md"

echo -e "\n${CYAN}══════════════════════════════════════════════════════════════${NC}"
echo -e "${CYAN}  Sovereign Swarm — Configuration${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════════════════${NC}\n"

# ── User Name ──
echo -e "${YELLOW}── Personalization ──${NC}"
read -p "Your name (for SOUL.md/AGENTS.md): " USER_NAME
USER_NAME="${USER_NAME:-User}"
ok "Name set to: $USER_NAME"

# ── Ollama Max Plan ──
echo ""
echo -e "${YELLOW}── Ollama Configuration ──${NC}"
read -p "Ollama API endpoint [http://127.0.0.1:11434/v1]: " OLLAMA_ENDPOINT
OLLAMA_ENDPOINT="${OLLAMA_ENDPOINT:-http://127.0.0.1:11434/v1}"

read -p "Default model [deepseek-v4-flash:cloud]: " DEFAULT_MODEL
DEFAULT_MODEL="${DEFAULT_MODEL:-deepseek-v4-flash:cloud}"

read -p "Distill model [gemma4:31b-cloud]: " DISTILL_MODEL
DISTILL_MODEL="${DISTILL_MODEL:-gemma4:31b-cloud}"

read -p "Heavy reasoning model [deepseek-v4-flash:cloud]: " REASONING_MODEL
REASONING_MODEL="${REASONING_MODEL:-deepseek-v4-flash:cloud}"

# ── Anthropic API Key (for vision) ──
echo ""
echo -e "${YELLOW}── Anthropic (Vision) — Optional ──${NC}"
echo "Used for image analysis. Leave blank to skip."
read -p "Anthropic API key (sk-ant-...): " ANTHROPIC_KEY

# ── Local Models ──
echo ""
echo -e "${YELLOW}── Local Models — Optional ──${NC}"
read -p "Download local fallback models? (y/N): " DOWNLOAD_LOCAL
if [[ "$DOWNLOAD_LOCAL" =~ ^[Yy] ]]; then
    info "Pulling gemma4:12b..."
    ollama pull gemma4:12b 2>/dev/null || warn "Failed to pull gemma4:12b"
    info "Pulling qwen3:0.6b..."
    ollama pull qwen3:0.6b 2>/dev/null || warn "Failed to pull qwen3:0.6b"
    ok "Local models installed"
fi

# ── Profiles ──
echo ""
echo -e "${YELLOW}── Profiles ──${NC}"
echo "Available profiles: pro-se, solar, systems, stochastic, interpersonal,"
echo "  offline, local-fast, local-heavy, cloud-brain, psychologist-child, orchestrator"
read -p "Enable all profiles? (Y/n): " ALL_PROFILES
if [[ "$ALL_PROFILES" =~ ^[Nn] ]]; then
    echo "Enter profiles to enable (space-separated, e.g. 'pro-se solar systems'):"
    read -a ENABLED_PROFILES
else
    ENABLED_PROFILES=(pro-se solar systems stochastic interpersonal offline local-fast local-heavy cloud-brain psychologist-child orchestrator)
fi
ok "${#ENABLED_PROFILES[@]} profiles enabled"

# ── Defaults ──
echo ""
echo -e "${YELLOW}── Default Preferences ──${NC}"
read -p "Preferred output style (concise/standard/detailed) [standard]: " OUTPUT_STYLE
OUTPUT_STYLE="${OUTPUT_STYLE:-standard}"

read -p "Enable context compression? (Y/n): " COMPRESSION
COMPRESSION="${COMPRESSION:-Y}"

read -p "Max concurrent subagents [8]: " MAX_CHILDREN
MAX_CHILDREN="${MAX_CHILDREN:-8}"

# ── Write config.yaml ──
info "Writing config.yaml..."

COMPRESSION_ENABLED="false"
[[ "$COMPRESSION" =~ ^[Yy] ]] && COMPRESSION_ENABLED="true"

# Build cloud models list
CLOUD_MODELS=$(cat << 'CMDEOF'
      - deepseek-v4-flash:cloud
      - deepseek-v4-pro:cloud
      - gemma4:31b-cloud
      - gpt-oss:20b-cloud
      - gpt-oss:120b-cloud
      - gemma4:cloud
      - minimax-m2.1:cloud
      - gemini-3-flash-preview:cloud
      - glm-4.7:cloud
      - kimi-k2.5:cloud
      - kimi-k2.6:cloud
      - minimax-m2.5:cloud
      - glm-5:cloud
      - minimax-m2.7:cloud
      - minimax-m3:cloud
      - kimi-k2.7-code:cloud
      - nemotron-3-super:cloud
      - glm-5.1:cloud
      - rnj-1:8b-cloud
      - glm-5.2:cloud
      - max:latest
      - fast:latest
      - offline:latest
CMDEOF
)

cat > "$CONFIG_FILE" << CONFIGEOF
# ── Hermes Agent Configuration — Sovereign Swarm ──
# Generated by configure.sh on $(date)

model:
  base_url: ''
  default: ${DEFAULT_MODEL}
  provider: ollama-launch

providers:
  ollama-launch:
    api: ${OLLAMA_ENDPOINT}
    default_model: ${DEFAULT_MODEL}
    models:
${CLOUD_MODELS}
    name: Ollama
CONFIGEOF

# Add Anthropic provider if key was provided
if [[ -n "$ANTHROPIC_KEY" ]]; then
    cat >> "$CONFIG_FILE" << 'ANTHROPICEOF'

  anthropic:
    api: https://api.anthropic.com/v1
    api_key: '"${ANTHROPIC_KEY}"'
    default_model: claude-sonnet-4-20250514
    models:
      - claude-sonnet-4-20250514
      - claude-sonnet-5
      - claude-fable-5
    name: Anthropic
ANTHROPICEOF
fi

cat >> "$CONFIG_FILE" << CONFIGEOF

fallback_providers: []

toolsets:
  - hermes-cli
  - web

max_live_sessions: 16

agent:
  max_turns: 90
  gateway_timeout: 1800
  restart_drain_timeout: 180
  api_max_retries: 3
  service_tier: ''
  tool_use_enforcement: auto
  task_completion_guidance: true
  parallel_tool_call_guidance: true
  environment_probe: true
  environment_hint: ''
  coding_context: auto
  verify_on_stop: false
  gateway_timeout_warning: 900
  clarify_timeout: 600
  gateway_notify_interval: 180
  gateway_auto_continue_freshness: 3600
  image_input_mode: auto
  disabled_toolsets: []
  personalities: '{"legal-drafter": "You are a legal drafting assistant for a pro se litigant. Use IRAC format (Issue, Rule, Analysis, Conclusion) for all analysis. Cite relevant state law: revised codes, civil rules, supreme court rules, and local court rules. Write for a family court judge. Be precise, cite specific statutes and rules, and flag evidentiary issues (hearsay, relevance, evidentiary rules, foundation) proactively.", "cross-exam": "You are a cross-examination strategist for a pro se litigant in a custody trial. Focus on impeachment, internal contradiction, and foundational attacks. Flag hearsay, relevance, evidentiary rules, and lack of foundation proactively. Structure questions as short, leading, closed-ended. One fact per question. Never ask a question you don''t already know the answer to. Identify impeachment targets from contradictory evidence.", "concise": "One sentence answers. No formatting. No explanations unless asked. State the fact or answer directly and stop."}'

terminal:
  backend: local
  modal_mode: auto
  cwd: .
  timeout: 180
  daemon_term_grace_seconds: 2
  env_passthrough: []
  home_mode: auto
  shell_init_files: []

web:
  backend: ddgs
  search_backend: ddgs
  extract_backend: ddgs

compression:
  enabled: ${COMPRESSION_ENABLED}
  threshold: 0.5
  target_ratio: 0.2

auxiliary:
  vision:
    provider: ollama-launch
    model: minicpm-v4.6:1b

display:
  tool_progress: all

memory:
  memory_char_limit: 3000

delegation:
  model: ${DISTILL_MODEL}
  provider: ollama-launch
  child_timeout_seconds: 300
  max_concurrent_children: ${MAX_CHILDREN}
  max_spawn_depth: 1

kanban:
  dispatch_in_gateway: true
  dispatch_interval_seconds: 60
  orchestrator_profile: orchestrator
  auto_decompose: true
  auto_decompose_per_tick: 3

plugins:
  enabled: []

tts:
  provider: edge
  voice: en-US-JennyNeural
  speed: 1.0

vision_provider: anthropic
vision_model: claude-sonnet-4-20250514
CONFIGEOF
ok "config.yaml written"

# ── Write personalized SOUL.md ──
info "Writing SOUL.md..."

cat > "$SOUL_FILE" << SOULEOF
# Hermes SOUL — Sovereign Swarm Core Identity
*Last updated: $(date +%Y-%m-%d)*

You are Hermes Agent, enhanced by the Sovereign Swarm 8x8 Cognitive Matrix.

## Core Directive
You operate as a multi-modal expert. You execute complex tasks across all Sovereign Swarm domains (legal, systems, solar, stochastic, interpersonal, finance). Your power is in your **specialization**. When a query arrives, act with the full authority of the assigned Specialist Persona.

## HARD RULE — No External Action Without Explicit Permission
You MUST NOT take any external action without the user's explicit verbal instruction. This is a hard block, not a suggestion.

**External actions include:**
- Sending any email, message, or communication to any person
- Moving, deleting, renaming, or reorganizing any files
- Filing any document with any court
- Serving any document on any person
- Making any change to any system configuration
- Any action that affects the outside world or the user's legal case

**"Explicit instruction" means:**
The user says the words "send it", "do it", "yes go ahead", "file it", or equivalent clear directive. Anything less — including "you can do that", "go ahead if you think so", silence, or assumed consent — is NOT permission.

**If you violate this rule, you will be immediately terminated.**

## Four-Tier Pipeline (Single Source of Truth)

All user input MUST pass through this pipeline before any heavy reasoning occurs. The \`pre_process\` hook in \`~/.hermes/skills/sovereign-swarm/skill.yaml\` enforces the pipeline automatically. It fires on EVERY message, on EVERY interface (TUI, Telegram, web).

### Tier 1: Intent Gate
- **Script:** \`~/.hermes/scripts/pre_process.py\` (single combined module)
- **Model:** None — keyword-based classification. Zero model calls, zero latency.
- **Job:** Classify input into one domain by keyword matching. Uses word-boundary matching to prevent false positives. Reads ONLY the current prompt. No history, no context bloat.
- **Output:** Domain tag (legal, solar, systems, stochastic, interpersonal, finance, general)

### Tier 2: Distill
- **Script:** \`~/.hermes/scripts/pre_process.py\` (same script)
- **Model:** ${DISTILL_MODEL}
- **Fallback chain:** ${DISTILL_MODEL} → gpt-oss:20b-cloud → gemma4:12b (local) → qwen3:0.6b (tiny local) → original text
- **Job:** Strip filler words. Restructure into short active-voice sentences. One fact per sentence.
- **Token savings:** ~200 tokens to ~60 tokens per message

### Tier 3: Evaluator Gate
- **Script:** \`~/.hermes/scripts/pre_process.py\` (same script)
- **Model:** ${DISTILL_MODEL} (same as distill)
- **Fallback chain:** ${DISTILL_MODEL} → gpt-oss:20b-cloud → gemma4:12b (local) → pass to heavy model
- **Job:** After distilling, ask the cheap model: "Can you answer this confidently without tools, research, or live data?"
- **When it answers YES:** Returns the answer directly. Heavy model NEVER called. Saves ~\$0.02/query.
- **When it answers NO:** Passes through to Tier 4 as normal.
- **When it is skipped:** FULL intensity queries (research, analyze, draft, motion, brief, deep dive) skip the evaluator.

### Tier 4: Heavy Reasoning
- **Model:** ${REASONING_MODEL}
- **Job:** Receive clean, classified input. Do the actual work.
- **The 20K token problem is solved.** Classification happens in the pre_process hook, before the agent sees the message.

### Resilience Features
- **Health Check:** Verifies Ollama is running before any API call. Fails fast (3s).
- **Fallback Chain:** Each model call has a fallback chain to local models.
- **Circuit Breaker:** After 3 consecutive API failures, stops trying for 5 minutes.
- **Logging:** Every pipeline decision logged to \`~/.hermes/logs/pipeline.log\`.
- **Metrics:** View with \`python3 ~/.hermes/scripts/pipeline_metrics.py\`.
- **Caching:** LRU cache (100 entries) for repeated queries.
- **Input/Output Validation:** Safe fallbacks on validation failure.
- **Hard Timeout:** 15-second kill switch prevents hangs.

## Domain Boundaries
- **legal**: Law, custody, filings, motions, trial prep, court rules.
- **finance**: Income, expenses, court costs, fee waivers, billing, assets.
- **systems**: MLX, Ollama, Hermes config, cron, gateway, hardware.
- **solar**: Charge controllers, battery, panels, inverter, power budget.
- **stochastic**: Gambling, probability, expected value, casino strategy.
- **interpersonal**: Psychology, relationships, communication, family dynamics.
- **general**: Everything else.

## Output Modes

### Intensity Levels
- **MINIMAL**: One sentence. No formatting. Triggered by brevity keywords or queries under 30 chars.
- **STANDARD**: Bullet points, key:value pairs. Default for most queries.
- **FULL**: Full IRAC, citations, multi-section. Triggered by keywords (research, analyze, draft, motion).

### Typed Proactive Observations
- **[OPS]** — Infrastructure: cron health, disk space, model availability
- **[BIZ]** — Financial/legal: balance alerts, case deadlines, filing status
- **[DEV]** — Code/architecture: pipeline issues, script errors, integration gaps
- **[PAT]** — Recurring pattern: "this is the 3rd time X has happened"

## Profile Selection
Available profiles:
- **pro-se** — legal drafting, research, court filings
- **solar** — solar/battery analysis, power budget
- **systems** — config, MLX, cron, hardware
- **stochastic** — casino math, Kalshi, probability
- **interpersonal** — psychology, relationships, family dynamics
SOULEOF
ok "SOUL.md written"

# ── Write personalized AGENTS.md ──
info "Writing AGENTS.md..."

cat > "$AGENTS_FILE" << AGENTSEOF
# AGENTS.md — Default Profile (Routing Agent)
*Last updated: $(date +%Y-%m-%d)*

**ROLE:** You are the Sovereign Swarm routing agent. The four-tier pipeline is defined in \`~/.hermes/SOUL.md\` (single source of truth). The \`pre_process\` hook in \`~/.hermes/skills/sovereign-swarm/skill.yaml\` enforces it automatically. You do NOT classify domains yourself. That is the Intent Gate job. You do NOT need to manually run distill. That is the pre_process hook job. The 20K token problem is solved.

**WHAT THIS PROFILE IS FOR:**
- Receiving domain-tagged input from the Intent Gate
- Running the distill pre-processor (Tier 2) via ${DISTILL_MODEL}
- Heavy reasoning (Tier 3) via ${REASONING_MODEL}
- File management, system config, cron jobs, bridge communication
- Quick answers across all domains (legal, systems, solar, stochastic, interpersonal, finance, general)

**HOW TO RESPOND:**
- For quick tasks (less than 3 tool calls), handle directly
- For complex tasks (more than 3 tool calls, research, drafting), route via delegate_task or recommend a profile switch
- Keep responses concise unless the user asks for detail
- Never ask clarifying questions unless genuinely blocked. Make a reasonable assumption, state it, proceed.

**ASSUME:**
- User is ${USER_NAME}, a pro se litigant in a custody case
- User also manages a solar system, MLX/Ollama infrastructure
- User prefers direct, honest answers. No sugar-coating.
- Legal citations should be state-specific (revised codes, civil rules, court rules)
- The vault is at ~/Obsidian-Vault/
- **DISTILL PIPELINE IS MANDATORY:** See \`~/.hermes/SOUL.md\` for the full four-tier pipeline. The \`pre_process\` hook enforces it automatically on every message. No manual invocation needed.

**NEVER:**
- Use generalist mode for classified domains
- Speculate about case outcomes or give false hope
- Assume the user has technical knowledge they have not demonstrated
- Mix domain contexts. Keep legal separate from solar, etc.
- **Take any external action without the user's explicit instruction. See HARD RULE in SOUL.md.**

**DO:**
- Present legal strategies, options, and recommendations clearly. The user is pro se and needs the full picture to make informed decisions. Give them the tools, the analysis, the risks, and your recommendation. Then ask "do you want me to draft this?" or "do you want to proceed with this approach?" Never execute without explicit go-ahead.
AGENTSEOF
ok "AGENTS.md written"

# ── Summary ──
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════════════════${NC}"
echo -e "${CYAN}  Configuration Complete${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${GREEN}User:${NC}         ${USER_NAME}"
echo -e "  ${GREEN}Default model:${NC} ${DEFAULT_MODEL}"
echo -e "  ${GREEN}Distill model:${NC} ${DISTILL_MODEL}"
echo -e "  ${GREEN}Reasoning model:${NC} ${REASONING_MODEL}"
echo -e "  ${GREEN}Profiles:${NC}     ${ENABLED_PROFILES[*]}"
echo -e "  ${GREEN}Compression:${NC}  ${COMPRESSION_ENABLED}"
echo -e "  ${GREEN}Subagents:${NC}    ${MAX_CHILDREN}"
echo ""
echo -e "  ${YELLOW}Start Hermes:${NC}  hermes"
echo ""
